name: sync-to-marketing-site
on:
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: source branch
        default: develop
        required: true
      targetBranch:
        description: target branch
        default: develop
        required: true 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sourceBranch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: placeholder
          token: ${{ secrets.GH_PAT }}
          repository-name: cmsflexc/flexcompute.com
          target-folder: notebooks
          branch: ${{ inputs.targetBranch }} 
